name: Docker Image CI
run-name: ${{github.sha}} from ${{github.triggering_action}} by @${{github.actor}}

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: logIN
        run: docker login -u ylim -p ${{ secrets.DOCKERHUB_PASS }}
      
      - name: build build build
        env:
          BUILD_IMAGE: ylim/hello-world:${{ github.sha }}
          CACHE_IMAGE: ylim/hello-world:cache
        run: |
          docker pull $CACHE_IMAGE || echo "No cache image available. Skipping..."
          docker build --cache-from $CACHE_IMAGE -t $BUILD_IMAGE .
          docker rmi $CACHE_IMAGE
          docker tag $BUILD_IMAGE $CACHE_IMAGE
          docker push --all-tags ylim/hello-world

  nap:
    runs-on: ubuntu-latest
    outputs:
      example: derp
    steps:
      - name: sleepytime
        run: sleep 150

  rubocop:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: logIN
        run: docker login -u ylim -p ${{ secrets.DOCKERHUB_PASS }}
      
      - name: copz
        env:
          BUILD_IMAGE: ylim/hello-world:${{ github.sha }}
        run: docker run $BUILD_IMAGE bundle exec rubocop app

  rspec:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: logIN
        run: docker login -u ylim -p ${{ secrets.DOCKERHUB_PASS }}
      
      - name: test test test
        env:
          BUILD_IMAGE: ylim/hello-world:${{ github.sha }}
        run: docker run $BUILD_IMAGE bundle exec rspec

  rspec2:
    runs-on: ubuntu-latest
    needs: rspec
    steps:
      - name: logIN
        run: docker login -u ylim -p ${{ secrets.DOCKERHUB_PASS }}
      
      - name: test test test
        env:
          BUILD_IMAGE: ylim/hello-world:${{ github.sha }}
        run: docker run $BUILD_IMAGE bundle exec rspec
  rspec3:
    runs-on: ubuntu-latest
    needs: rspec
    steps:
      - name: logIN
        run: docker login -u ylim -p ${{ secrets.DOCKERHUB_PASS }}
      
      - name: test test test
        env:
          BUILD_IMAGE: ylim/hello-world:${{ github.sha }}
        run: docker run $BUILD_IMAGE bundle exec rspec

  message:
    runs-on: ubuntu-latest
    needs: [rspec2, rspec3, nap, rubocop]

    # outputs:
    #   output1: ${{ steps.step1.outputs.test }}
    #   output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: generate output
        run: echo "thing=initial" >> "$GITHUB_OUTPUT"
      - name: regenerate output 
        run: echo "thing=agane" >> "$GITHUB_OUTPUT"
      - name: issue messages
        run: |
          echo "::notice file=Dockerfile,line=3,col=1,endColumn=20::This is a notice for Dockerfile line 3, col 1-20!"
          echo '::warning file=Gemfile:: This is an example warning with the .example output of the sleep job: ${{ needs.nap.outputs.example }} !'
          echo '::error file:: This is an error with the list of step outputs: ${{ steps.*.outputs.* }} OR ${{ steps.*.outputs.thing }}!'
        
  update_qovery:
    needs: [build, rspec, rubocop]
    runs-on: ubuntu-latest
    if: github.ref_name	== 'main'
    steps:
      - id: update-blueprint-environment
        name: Update the Qovery blueprint environment
        env:
          QOVERY_CLI_ACCESS_TOKEN: ${{ secrets.QOVERY_CLI_ACCESS_TOKEN }}
        run: |
          # Download and install Qovery CLI
          curl -s https://get.qovery.com | bash

          echo "Organization name: ${{ vars.QOVERY_ORGANIZATION_NAME }}"
          echo "Project name: ${{ vars.QOVERY_PROJECT_NAME }}"
          echo "Blueprint name: ${{ vars.QOVERY_BLUEPRINT_ENVIRONMENT_NAME }}"
          echo "App name: ${{ vars.QOVERY_APPLICATION_NAME }}"

          qovery container update \
            --organization "${{ vars.QOVERY_ORGANIZATION_NAME }}" \
            --project "${{ vars.QOVERY_PROJECT_NAME }}" \
            --environment "${{ vars.QOVERY_BLUEPRINT_ENVIRONMENT_NAME }}" \
            --container "${{ vars.QOVERY_APPLICATION_NAME }}" \
            --tag ${{ github.sha }}

          qovery environment deploy \
            --organization "${{ vars.QOVERY_ORGANIZATION_NAME }}" \
            --project "${{ vars.QOVERY_PROJECT_NAME }}" \
            --environment "${{ vars.QOVERY_BLUEPRINT_ENVIRONMENT_NAME }}" \
            -w

        
