name: Docker Image CI
run-name: ${{github.sha}} from ${{github.triggering_action}} by @${{github.actor}}

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: build build build
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: docker build -t hello-world:$IMAGE_TAG .
