name: Docker Image CI
run-name: ${{github.sha}} from ${{github.triggering_action}} by @${{github.actor}}

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: logIN
        run: docker login -u ylim -p ${{ secrets.DOCKERHUB_PASS }}
      
      - name: build build build
        env:
          BUILD_IMAGE: ylim/hello-world:${{ github.sha }}
          CACHE_IMAGE: ylim/hello-world:cache
        run: |
          docker pull $CACHE_IMAGE || echo "No cache image available. Skipping..."
          docker build --cache-from $CACHE_IMAGE -t $BUILD_IMAGE .
          docker rmi $CACHE_IMAGE
          docker tag $BUILD_IMAGE $CACHE_IMAGE
          docker push --all-tags ylim/hello-world

  rubocop:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: logIN
        run: docker login -u ylim -p ${{ secrets.DOCKERHUB_PASS }}
      
      - name: copz
        env:
          BUILD_IMAGE: ylim/hello-world:${{ github.sha }}
        run: docker run $BUILD_IMAGE bundle exec rubocop app

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: logIN
        run: docker login -u ylim -p ${{ secrets.DOCKERHUB_PASS }}
      
      - name: test test test
        env:
          BUILD_IMAGE: ylim/hello-world:${{ github.sha }}
        run: docker run $BUILD_IMAGE bundle exec rspec


        
