on:
  push:
    branches:
      - main

jobs:
  details:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "::notice::COMMIT: ${{ github.sha }} TRIGGERED BY MERGE: ${{ github.ref }} BEFORE: ${{ github.event.push.before }}" AFTER: ${{ github.event.push.after }} PUSHER ${{ github.event.pusher.name}}"
